# Generated by Django 3.1.1 on 2021-07-15 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_images'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
    ]
